RNG_Text_HelloThere:
    .string "Hello there.\p"
    .string "I am hired by the dev to conduct\n"
    .string "a Pokemon RNG for players in here.$"

RNG_Text_EnterGacha:
    .string "Do you want to enter the RNG?\n"
    .string "I require a METAL ALLOY as entry fees.$"

RNG_Text_HaveANiceDay:
    .string "I see,\n"
    .string "have a nice day!$"

RNG_Text_DoStartGambling:
    .string "Okay, do you want to start\n"
    .string "the RNG?$"

RNG_Text_RecievedMonPC: @ Unused
    .string "Sent Pokemon to PC$"

RNG_Text_YouDontHaveMetalAlloy:
    .string "Sorry, but it looks like you\n"
    .string "don't have a METAL ALLOY.\l"
    .string "You cannot enter the RNG.$"

RNG_Text_NoRoomInPC: @ Unused
    .string "The PC is full.$"

Uncommon_Text_Cua:
    .string "Thanks for participating!\n"
    .string "Have a nice day!$"

Uncommon_Text_WhyThisMetal:
    .string "A metal piece lands out of\n"
    .string "nowhere on your palm.....$"

RNG_Text_MidRNGDots:
    .string ".........................\n"
    .string ".........................\l"
    .string ".........................\p"
    .string ".........................\n"
    .string ".........................\l"
    .string ".........................$"

RNG_Text_CongratsYouWonA:
    .string "Congratulations!\p"
    .string "You have won a {PLAY_BGM MUS_OBTAIN_BADGE}{STR_VAR_1}!{WAIT_SE}$"

RNG_Text_DoYouWantToReadRarityBoard:
    .string "The rewards of the RNG are\n"
    .string "listed on this board.\p"
    .string "Do you want to read it?$"

RNG_Text_RarityBoard:
    .string "{COLOR RED}PSEUDO LEGENDARY {COLOR DARK_GRAY}REWARDS\p"
    .string "{COLOR RED}DRATINI, LARVITAR, BELDUM,\n"
    .string "VOLCANION, DEINO, GOOMY,BAGON,\l"
    .string "JANGMO_O, XURKITREE, SLAKOTH\p"
    .string "{COLOR BLUE}RARE {COLOR DARK_GRAY}REWARDS\p"
    .string "{COLOR BLUE}DUCKLETT, SIGILYPH, ROCKRUFF,\n"
    .string "EEVEE, GASTLY, MAREEP, ELEKID,\l"
    .string "BUNEARY, RIOLU, SKARMORY\p"
    .string "{COLOR GREEN}UNCOMMON {COLOR DARK_GRAY}REWARDS\p"
    .string "{COLOR GREEN}MANTINE, CHATOT, CRABRAWLER,\n"
    .string "SPRITZEE, TYROGUE, TRAPINCH,\l"
    .string "DODUO, MUNCHLAX, SKITTY, WOOBAT,\p"
    .string "PANSAGE, PANSEAR, PANPOUR\p"
    .string "{COLOR WHITE}{SHADOW DARK_GRAY}COMMON {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}REWARDS\p"
    .string "{COLOR WHITE}{SHADOW DARK_GRAY}STUNFISK, POLIWAG, COMFEY,\n"
    .string "BIDOOF, EXEGGCUTE, PATRAT,\l"
    .string "STARLY, SCATTERBUG, WURMPLE,\p"
    .string "PIDGEY, RATTATA, TAILLOW,\p"
    .string "SENTRET, NINCADA, EKANS, MACHOP\n"
    .string "ZIGZAGOON, LEAVANNY, LILEEP{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}$"
