RNG_Text_HelloThere:
    .string "Hello there.\p"
    .string "I am hired by the dev to conduct\n"
    .string "a Pokemon RNG here for players.$"

RNG_Text_EnterGacha:
    .string "Do you want to enter the RNG?\n"
    .string "I require a METAL ALLOY as entry fees.$"

RNG_Text_HaveANiceDay:
    .string "I see,\n"
    .string "have a nice day!$"

RNG_Text_DoStartGambling:
    .string "Okay, do you want to start\n"
    .string "the RNG?$"

RNG_Text_RecievedMonPC: @ Unused
    .string "Sent Pokemon to PC$"

RNG_Text_YouDontHaveMetalAlloy:
    .string "Sorry, but it looks like you\n"
    .string "don't have a METAL ALLOY.\l"
    .string "You cannot enter the RNG.$"

RNG_Text_NoRoomInPC: @ Unused
    .string "The PC is full.$"

Uncommon_Text_Cua:
    .string "Thanks.$"

Uncommon_Text_WhyThisMetal:
    .string "A metal piece lands out of\n"
    .string "nowhere on your palm.....$"
